# 国际
DOMAIN-SUFFIX,staticfile.org,REJECT
DOMAIN-SUFFIX,stream1.freetv.fun,REJECT
DOMAIN-SUFFIX,formdesigner.pro,REJECT
DOMAIN-SUFFIX,alwingulla.com,REJECT
DOMAIN-SUFFIX,cfss.cc,REJECT
DOMAIN-SUFFIX,staticfile.net,REJECT
DOMAIN-SUFFIX,chajianxw.com,REJECT
DOMAIN-SUFFIX,explodasclksec.com,REJECT

# 微软遥测与隐私数据上报
DOMAIN,mobile.events.data.microsoft.com,REJECT

# 字节穿山甲 (核心广告拦截)
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao-b.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,REJECT
DOMAIN,api-access.pangolin-sdk-toutiao-b.com,REJECT
# 腾讯广点通
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,sdk.e.qq.com,REJECT
DOMAIN-SUFFIX,gdtimg.com,REJECT
# 阿里 Tanx & 友盟
DOMAIN-SUFFIX,tanx.com,REJECT
DOMAIN-SUFFIX,umeng.com,REJECT
DOMAIN-SUFFIX,umengcloud.com,REJECT
# 其他纯广告与归因追踪
DOMAIN-SUFFIX,520yidui.com,REJECT
DOMAIN-SUFFIX,adjust.cn,REJECT
DOMAIN-SUFFIX,shuzilm.cn,REJECT
DOMAIN-SUFFIX,ctobsnssdk.com,REJECT
DOMAIN-SUFFIX,pglstatp-toutiao.com,REJECT

# ================================
# 以下为精准拦截（DOMAIN），防止误杀主域名或公共 CDN
# ================================

# 拦截火山引擎中的风控探针与监控组件（保留了其他视频云的正常连接）
DOMAIN,mssdk.volces.com,REJECT
DOMAIN,apmplus.volces.com,REJECT

# 拦截字节全局网络调度节点 (阻止后续广告下发链路)
DOMAIN,tnc3-alisc1.zijieapi.com,REJECT

# 拦截京东的商业推广与联盟接口
DOMAIN,dg.k.jd.com,REJECT
DOMAIN,dgstatic.jd.com,REJECT

# 拦截阿里/淘宝的 UT 用户行为打点
DOMAIN,adashbc.ut.taobao.com,REJECT
DOMAIN,adashxgc.ut.taobao.com,REJECT
