DOMAIN-SUFFIX,staticfile.org,REJECT
DOMAIN-SUFFIX,stream1.freetv.fun,REJECT
DOMAIN-SUFFIX,formdesigner.pro,REJECT
DOMAIN-SUFFIX,alwingulla.com,REJECT
DOMAIN-SUFFIX,cfss.cc,REJECT
DOMAIN-SUFFIX,staticfile.net,REJECT
DOMAIN-SUFFIX,chajianxw.com,REJECT
DOMAIN-SUFFIX,explodasclksec.com,REJECT
