# 需要走代理的域名（被误判直连的修正）
DOMAIN-SUFFIX,vanced.to,Proxy # YouTube Vanced / ReVanced 相关
DOMAIN-SUFFIX,workers.dev,Proxy # Cloudflare Workers 部署的服务
DOMAIN-SUFFIX,gstatic.com,Proxy # Google 静态资源
# Google 相关 IP 范围
IP-CIDR,64.233.0.0/16,Proxy,no-resolve
IP-CIDR,64.233.0.0/16,Proxy,no-resolve
IP-CIDR,108.177.0.0/16,Proxy,no-resolve
IP-CIDR,142.250.0.0/15,Proxy,no-resolve
IP-CIDR,172.217.0.0/16,Proxy,no-resolve
IP-CIDR,216.58.192.0/19,Proxy,no-resolve;
