# ───── Google Play Store 直连 ─────
DOMAIN-SUFFIX,services.googleapis.cn,DIRECT
DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT
# ───── 自有 IP 直连 ─────
IP-CIDR,216.36.116.51/32,DIRECT,no-resolve
IP-CIDR,66.80.0.225/32,DIRECT,no-resolve
IP-CIDR,104.225.149.20/32,DIRECT,no-resolve
IP-CIDR,168.93.214.76/32,DIRECT,no-resolve
