# ───── Google Play Store 直连 ─────
DOMAIN-SUFFIX,services.googleapis.cn,DIRECT
DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT
# ───── 自有 IP 直连 ─────
IP-CIDR,216.36.116.0/24,DIRECT,no-resolve
IP-CIDR,66.80.0.0/24,DIRECT,no-resolve
IP-CIDR,104.225.149.0/24,DIRECT,no-resolve
IP-CIDR,168.93.214.0/24,DIRECT,no-resolve
